apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: yetroid-backend-config
spec:
  timeoutSec: 3600 # 1 hour timeout for WebSocket connections
  connectionDraining:
    drainingTimeoutSec: 300
  sessionAffinity:
    affinityType: "CLIENT_IP" # Ensures WebSocket connections stick to same pod
  logging:
    enable: true
    sampleRate: 1.0
